# Generated by Django 4.0.5 on 2022-10-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=500)),
                ('m_domain', models.IntegerField()),
                ('s_domain', models.IntegerField()),
                ('area', models.FloatField()),
                ('floor', models.IntegerField()),
                ('year', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'multi',
                'ordering': ['-addr'],
            },
        ),
    ]
